# Generated by Django 5.0.3 on 2024-03-11 20:20

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inventoryAvatar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('TL', 'Turtle'), ('DK', 'Duck'), ('CT', 'Cat')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='inventoryDecoration',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(class)s_decorations_stored', to='app_user.decoration'),
        ),
    ]
