# Generated by Django 5.0.3 on 2024-03-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_user_inventoryavatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inventoryDecoration',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_decorations_stored', to='app_user.decoration'),
        ),
    ]
