# Generated by Django 5.0.3 on 2024-03-11 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_user_inventorydecoration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_decoration_used', to='app_user.decoration'),
        ),
    ]
