# Generated by Django 5.0.3 on 2024-03-11 20:25

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_alter_user_decoration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('TL', 'Turtle'), ('DK', 'Duck'), ('CT', 'Cat'), ('NA', 'No Avatar')], default='NA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='inventoryAvatar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('TL', 'Turtle'), ('DK', 'Duck'), ('CT', 'Cat'), ('NA', 'No Avatar')], max_length=2, null=True),
        ),
    ]
