# Generated by Django 5.0.3 on 2024-03-11 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_alter_user_avatar_alter_user_inventoryavatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='inventoryAvatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_avatar_used', to='app_user.avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='inventoryAvatar',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_avatars_stored', to='app_user.avatar'),
        ),
    ]
